{
 "title": "Main dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency Q0.50",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.5,\r\n    sum(\r\n      rate(\r\n        http_request_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le, handler, method )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Q0.95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(\r\n      rate(\r\n        http_request_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le, handler, method )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Q0.99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.99,\r\n    sum(\r\n      rate(\r\n        http_request_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le, handler, method )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Q1.00",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    1.00,\r\n    sum(\r\n      rate(\r\n        http_request_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le, handler, method )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by(handler, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~'5..'}[1m])) by (handler, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nginx Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Latency по квантилям",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.5,\r\n    sum(\r\n      rate(\r\n        nginx_ingress_controller_response_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le)\r\n)",
     "legendFormat": "Q 0.50"
    },
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(\r\n      rate(\r\n        nginx_ingress_controller_response_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le)\r\n)",
     "legendFormat": "Q 0.95"
    },
    {
     "expr": "histogram_quantile(\r\n    0.99,\r\n    sum(\r\n      rate(\r\n        nginx_ingress_controller_response_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le)\r\n)",
     "legendFormat": "Q 0.99"
    },
    {
     "expr": "histogram_quantile(\r\n    1,\r\n    sum(\r\n      rate(\r\n        nginx_ingress_controller_response_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le)\r\n)",
     "legendFormat": "Q max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(sum(rate(nginx_ingress_controller_requests{status=~'5..'}[1m])) by (ingress,cluster) or on() vector(0))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}