apiVersion: v1
kind: Service
metadata:
  name: fasthealth-svc
  labels:
    app: fasthealth-dp
spec:
  selector:
    env: dev
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP