apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasthealth-dp
  labels:
    app: fasthealth-dp
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: fasthealth-app
        image: belokrilov/users:v1
        imagePullPolicy: Always
        env:
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: PG_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: pgport
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: dbname
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: pghost
        ports:
        - containerPort: 8000 